import Browser from "../adapters/browser";

export class GeminiHelper {
  static async getApiKey(): Promise<string> {
    const res = await Browser.storage.local.get({
      geminiApiKey: ""
    });
    return res.geminiApiKey || "";
  }

  static async setApiKey(key: string): Promise<void> {
    await Browser.storage.local.set({
      geminiApiKey: key.trim()
    });
  }

  static async callGemini(prompt: string, systemInstruction?: string): Promise<string> {
    const apiKey = await this.getApiKey();
    if (!apiKey) {
      throw new Error("Missing Gemini API Key. Please add it in Settings.");
    }

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              role: "user",
              parts: [{ text: prompt }],
            },
          ],
          systemInstruction: systemInstruction
            ? {
                parts: [{ text: systemInstruction }],
              }
            : undefined,
          generationConfig: {
            temperature: 0.2,
          },
        }),
      }
    );

    if (!response.ok) {
      const err = await response.json().catch(() => ({}));
      const message = err?.error?.message || `HTTP ${response.status}`;
      throw new Error(`Gemini API Error: ${message}`);
    }

    const json = await response.json();
    const candidateText = json?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidateText) {
      throw new Error("No response content generated by Gemini.");
    }
    return candidateText.trim();
  }

  static async autoTag(promptText: string): Promise<string> {
    const system = "You are a prompt categorizer. Return only a comma-separated list of 2 to 4 simple lowercase tags suitable for categorizing this prompt. Do not write anything else. Do not output markdown, prefixes, quotes, or conversational explanations.";
    return this.callGemini(promptText, system);
  }

  static async improve(promptText: string): Promise<string> {
    const system = "You are a prompt engineer. Enhance the input prompt to make it more precise, structured, clear, and context-rich. Keep the same core intent but improve formatting, instructions, and placeholder variables. Output only the improved prompt text itself.";
    return this.callGemini(promptText, system);
  }

  static async shorten(promptText: string): Promise<string> {
    const system = "You are a concise editor. Condense the input prompt to make it significantly shorter, punchy, and direct, removing redundancy while keeping its core instruction. Output only the shortened prompt text.";
    return this.callGemini(promptText, system);
  }
}
